trigger:
- main

resources:
- repo: self

parameters:
- name: tag
  default: "$(Build.BuildId)"

- name: imageName
  default: "test-page"

stages:

- stage: Build

  jobs:

  - job: Build

    pool:
      name: local-agent

    steps:

    - task: Docker@2
      displayName: Build

      inputs:
        command: build
        repository: ${{ parameters.imageName }}
        dockerfile: "**/Dockerfile"
        tags: ${{ parameters.tag }}
        containerRegistry: registryConnection

    - task: Docker@2
      displayName: Push

      inputs:
        command: push
        repository: ${{ parameters.imageName }}
        tags: ${{ parameters.tag }}
        containerRegistry: testPageDeployConnection

- stage: Deploy

  dependsOn: Build

  jobs:

  - job: Deploy

    pool:
      name: local-agent

    steps:

    - task: AzureContainerApps@1

      inputs:

        azureSubscription: testPageDeployConnection

        imageToDeploy: t1cenfo.azurecr.io/${{ parameters.imageName }}:${{ parameters.tag }}

        containerAppName: test-page

        resourceGroup: rg-devops